version: "3.9"
services:
  tel-bot:
    image: ghcr.io/lizqwerscott/tel-bot:latest
    volumes:
      - ./configs:/root/.tel-bot/
      - ./downloads:/root/downloads/
    command: sbcl --load start.lisp
